#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 37
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 6

enum ts_symbol_identifiers {
  sym_commentLine = 1,
  anon_sym_LBRACE_DASH = 2,
  anon_sym_DASH_RBRACE = 3,
  aux_sym__endComment_token1 = 4,
  sym_sym = 5,
  sym_nat = 6,
  sym_levelT = 7,
  anon_sym_COMMA = 8,
  anon_sym_PLUS = 9,
  anon_sym_POUNDU = 10,
  anon_sym_AT = 11,
  anon_sym_EQ = 12,
  anon_sym_SEMI = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  sym_erased = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COLON = 18,
  anon_sym_RPAREN = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  anon_sym_SLASH_BSLASH = 22,
  anon_sym_COLON_GT = 23,
  anon_sym_CARET = 24,
  aux_sym_postIntersection_token1 = 25,
  sym_expr = 26,
  sym__comment = 27,
  sym_commentBlock = 28,
  sym__endComment = 29,
  sym_levels = 30,
  sym__level = 31,
  sym_levelAdd = 32,
  sym_universe = 33,
  sym_named = 34,
  sym_bracket = 35,
  sym_lambda = 36,
  sym_erasedLambda = 37,
  sym_intersectionT = 38,
  sym_opTyped = 39,
  sym_opIntersection = 40,
  sym_opApp = 41,
  sym__baseExpr = 42,
  sym__preComments = 43,
  sym__postComments = 44,
  sym_postIntersection = 45,
  sym__expr = 46,
  aux_sym_levels_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_commentLine] = "commentLine",
  [anon_sym_LBRACE_DASH] = "{- ",
  [anon_sym_DASH_RBRACE] = " -}",
  [aux_sym__endComment_token1] = "_endComment_token1",
  [sym_sym] = "sym",
  [sym_nat] = "nat",
  [sym_levelT] = "levelT",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_POUNDU] = "#U",
  [anon_sym_AT] = "@",
  [anon_sym_EQ] = " = ",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_erased] = "erased",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH_BSLASH] = "/\\",
  [anon_sym_COLON_GT] = ":>",
  [anon_sym_CARET] = "^",
  [aux_sym_postIntersection_token1] = "postIntersection_token1",
  [sym_expr] = "expr",
  [sym__comment] = "_comment",
  [sym_commentBlock] = "commentBlock",
  [sym__endComment] = "_endComment",
  [sym_levels] = "levels",
  [sym__level] = "_level",
  [sym_levelAdd] = "levelAdd",
  [sym_universe] = "universe",
  [sym_named] = "named",
  [sym_bracket] = "bracket",
  [sym_lambda] = "lambda",
  [sym_erasedLambda] = "erasedLambda",
  [sym_intersectionT] = "intersectionT",
  [sym_opTyped] = "opTyped",
  [sym_opIntersection] = "opIntersection",
  [sym_opApp] = "opApp",
  [sym__baseExpr] = "_baseExpr",
  [sym__preComments] = "_preComments",
  [sym__postComments] = "_postComments",
  [sym_postIntersection] = "postIntersection",
  [sym__expr] = "_expr",
  [aux_sym_levels_repeat1] = "levels_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_commentLine] = sym_commentLine,
  [anon_sym_LBRACE_DASH] = anon_sym_LBRACE_DASH,
  [anon_sym_DASH_RBRACE] = anon_sym_DASH_RBRACE,
  [aux_sym__endComment_token1] = aux_sym__endComment_token1,
  [sym_sym] = sym_sym,
  [sym_nat] = sym_nat,
  [sym_levelT] = sym_levelT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_POUNDU] = anon_sym_POUNDU,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_erased] = sym_erased,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH_BSLASH] = anon_sym_SLASH_BSLASH,
  [anon_sym_COLON_GT] = anon_sym_COLON_GT,
  [anon_sym_CARET] = anon_sym_CARET,
  [aux_sym_postIntersection_token1] = aux_sym_postIntersection_token1,
  [sym_expr] = sym_expr,
  [sym__comment] = sym__comment,
  [sym_commentBlock] = sym_commentBlock,
  [sym__endComment] = sym__endComment,
  [sym_levels] = sym_levels,
  [sym__level] = sym__level,
  [sym_levelAdd] = sym_levelAdd,
  [sym_universe] = sym_universe,
  [sym_named] = sym_named,
  [sym_bracket] = sym_bracket,
  [sym_lambda] = sym_lambda,
  [sym_erasedLambda] = sym_erasedLambda,
  [sym_intersectionT] = sym_intersectionT,
  [sym_opTyped] = sym_opTyped,
  [sym_opIntersection] = sym_opIntersection,
  [sym_opApp] = sym_opApp,
  [sym__baseExpr] = sym__baseExpr,
  [sym__preComments] = sym__preComments,
  [sym__postComments] = sym__postComments,
  [sym_postIntersection] = sym_postIntersection,
  [sym__expr] = sym__expr,
  [aux_sym_levels_repeat1] = aux_sym_levels_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_commentLine] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__endComment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_sym] = {
    .visible = true,
    .named = true,
  },
  [sym_nat] = {
    .visible = true,
    .named = true,
  },
  [sym_levelT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDU] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_erased] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_postIntersection_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_commentBlock] = {
    .visible = true,
    .named = true,
  },
  [sym__endComment] = {
    .visible = false,
    .named = true,
  },
  [sym_levels] = {
    .visible = true,
    .named = true,
  },
  [sym__level] = {
    .visible = false,
    .named = true,
  },
  [sym_levelAdd] = {
    .visible = true,
    .named = true,
  },
  [sym_universe] = {
    .visible = true,
    .named = true,
  },
  [sym_named] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_erasedLambda] = {
    .visible = true,
    .named = true,
  },
  [sym_intersectionT] = {
    .visible = true,
    .named = true,
  },
  [sym_opTyped] = {
    .visible = true,
    .named = true,
  },
  [sym_opIntersection] = {
    .visible = true,
    .named = true,
  },
  [sym_opApp] = {
    .visible = true,
    .named = true,
  },
  [sym__baseExpr] = {
    .visible = false,
    .named = true,
  },
  [sym__preComments] = {
    .visible = false,
    .named = true,
  },
  [sym__postComments] = {
    .visible = false,
    .named = true,
  },
  [sym_postIntersection] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_levels_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_rest = 3,
  field_type = 4,
  field_type1 = 5,
  field_type2 = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_rest] = "rest",
  [field_type] = "type",
  [field_type1] = "type1",
  [field_type2] = "type2",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
  [4] = {.index = 7, .length = 3},
  [5] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 3},
    {field_type, 1},
  [2] =
    {field_body, 3},
    {field_name, 1},
  [4] =
    {field_body, 3},
    {field_name, 1},
    {field_rest, 5},
  [7] =
    {field_body, 5},
    {field_name, 1},
    {field_type, 3},
  [10] =
    {field_name, 1},
    {field_type1, 3},
    {field_type2, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 51,
  [55] = 55,
  [56] = 56,
  [57] = 47,
  [58] = 45,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        ' ', 2,
        '#', 10,
        '\'', 34,
        '(', 35,
        ')', 37,
        '+', 27,
        ',', 26,
        '-', 7,
        '.', 12,
        '/', 11,
        ':', 36,
        ';', 31,
        '<', 38,
        '>', 39,
        '@', 29,
        '[', 32,
        ']', 33,
        '^', 42,
        '{', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 2,
        '#', 10,
        '\'', 34,
        '(', 35,
        ')', 37,
        '+', 27,
        ',', 26,
        '-', 7,
        '.', 12,
        '/', 11,
        ':', 36,
        ';', 31,
        '<', 38,
        '>', 39,
        '@', 29,
        '[', 32,
        ']', 33,
        '^', 42,
        '{', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 2,
        '#', 10,
        '\'', 34,
        '(', 35,
        ')', 37,
        '+', 27,
        ',', 26,
        '-', 8,
        '.', 12,
        '/', 11,
        ':', 36,
        ';', 31,
        '<', 38,
        '=', 3,
        '>', 39,
        '@', 29,
        '[', 32,
        ']', 33,
        '^', 42,
        '{', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '{') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '}') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == 'L') ADVANCE(25);
      if (lookahead == 'U') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == '\\') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == '1' ||
          lookahead == '2') ADVANCE(43);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_commentLine);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE_DASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '{') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '{') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '}') ADVANCE(16);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_sym);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_nat);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_levelT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_POUNDU);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_erased);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_BSLASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COLON_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_postIntersection_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_commentLine] = ACTIONS(1),
    [anon_sym_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_DASH_RBRACE] = ACTIONS(1),
    [sym_sym] = ACTIONS(1),
    [sym_nat] = ACTIONS(1),
    [sym_levelT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_POUNDU] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_erased] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH_BSLASH] = ACTIONS(1),
    [anon_sym_COLON_GT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [aux_sym_postIntersection_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_expr] = STATE(61),
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(16),
    [sym_named] = STATE(16),
    [sym_bracket] = STATE(16),
    [sym_lambda] = STATE(16),
    [sym_erasedLambda] = STATE(16),
    [sym_intersectionT] = STATE(16),
    [sym_opTyped] = STATE(16),
    [sym_opIntersection] = STATE(16),
    [sym_opApp] = STATE(16),
    [sym__baseExpr] = STATE(16),
    [sym__preComments] = STATE(16),
    [sym__postComments] = STATE(16),
    [sym_postIntersection] = STATE(16),
    [sym__expr] = STATE(16),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(7),
    [sym_nat] = ACTIONS(7),
    [sym_levelT] = ACTIONS(7),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [2] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(9),
    [sym_named] = STATE(9),
    [sym_bracket] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_erasedLambda] = STATE(9),
    [sym_intersectionT] = STATE(9),
    [sym_opTyped] = STATE(9),
    [sym_opIntersection] = STATE(9),
    [sym_opApp] = STATE(9),
    [sym__baseExpr] = STATE(9),
    [sym__preComments] = STATE(9),
    [sym__postComments] = STATE(9),
    [sym_postIntersection] = STATE(9),
    [sym__expr] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(21),
    [sym_nat] = ACTIONS(21),
    [sym_levelT] = ACTIONS(21),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(19),
    [sym_erased] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_SLASH_BSLASH] = ACTIONS(19),
    [anon_sym_COLON_GT] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(19),
    [aux_sym_postIntersection_token1] = ACTIONS(19),
  },
  [3] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(23),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_SLASH_BSLASH] = ACTIONS(23),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [4] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(37),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(37),
    [anon_sym_SLASH_BSLASH] = ACTIONS(37),
    [anon_sym_COLON_GT] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [5] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_SLASH_BSLASH] = ACTIONS(39),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [6] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(41),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(41),
    [anon_sym_SLASH_BSLASH] = ACTIONS(41),
    [anon_sym_COLON_GT] = ACTIONS(41),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [7] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(43),
    [sym_nat] = ACTIONS(43),
    [sym_levelT] = ACTIONS(43),
    [anon_sym_POUNDU] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [sym_erased] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_SLASH_BSLASH] = ACTIONS(43),
    [anon_sym_COLON_GT] = ACTIONS(43),
    [anon_sym_CARET] = ACTIONS(43),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [8] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(45),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(45),
    [anon_sym_SLASH_BSLASH] = ACTIONS(45),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [9] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_commentLine] = ACTIONS(47),
    [anon_sym_LBRACE_DASH] = ACTIONS(47),
    [sym_sym] = ACTIONS(47),
    [sym_nat] = ACTIONS(47),
    [sym_levelT] = ACTIONS(47),
    [anon_sym_POUNDU] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(47),
    [anon_sym_RBRACK] = ACTIONS(47),
    [sym_erased] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_SLASH_BSLASH] = ACTIONS(47),
    [anon_sym_COLON_GT] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(47),
    [aux_sym_postIntersection_token1] = ACTIONS(47),
  },
  [10] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(13),
    [sym_named] = STATE(13),
    [sym_bracket] = STATE(13),
    [sym_lambda] = STATE(13),
    [sym_erasedLambda] = STATE(13),
    [sym_intersectionT] = STATE(13),
    [sym_opTyped] = STATE(13),
    [sym_opIntersection] = STATE(13),
    [sym_opApp] = STATE(13),
    [sym__baseExpr] = STATE(13),
    [sym__preComments] = STATE(13),
    [sym__postComments] = STATE(13),
    [sym_postIntersection] = STATE(13),
    [sym__expr] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(51),
    [sym_nat] = ACTIONS(51),
    [sym_levelT] = ACTIONS(51),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(49),
    [sym_erased] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(49),
    [anon_sym_SLASH_BSLASH] = ACTIONS(49),
    [anon_sym_COLON_GT] = ACTIONS(49),
    [anon_sym_CARET] = ACTIONS(49),
    [aux_sym_postIntersection_token1] = ACTIONS(49),
  },
  [11] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(53),
    [sym_nat] = ACTIONS(53),
    [sym_levelT] = ACTIONS(53),
    [anon_sym_POUNDU] = ACTIONS(53),
    [anon_sym_AT] = ACTIONS(53),
    [anon_sym_SEMI] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(53),
    [anon_sym_RBRACK] = ACTIONS(53),
    [sym_erased] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_SLASH_BSLASH] = ACTIONS(53),
    [anon_sym_COLON_GT] = ACTIONS(53),
    [anon_sym_CARET] = ACTIONS(53),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [12] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(13),
    [sym_named] = STATE(13),
    [sym_bracket] = STATE(13),
    [sym_lambda] = STATE(13),
    [sym_erasedLambda] = STATE(13),
    [sym_intersectionT] = STATE(13),
    [sym_opTyped] = STATE(13),
    [sym_opIntersection] = STATE(13),
    [sym_opApp] = STATE(13),
    [sym__baseExpr] = STATE(13),
    [sym__preComments] = STATE(13),
    [sym__postComments] = STATE(13),
    [sym_postIntersection] = STATE(13),
    [sym__expr] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(51),
    [sym_nat] = ACTIONS(51),
    [sym_levelT] = ACTIONS(51),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(55),
    [sym_erased] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(55),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(55),
    [anon_sym_SLASH_BSLASH] = ACTIONS(55),
    [anon_sym_COLON_GT] = ACTIONS(55),
    [anon_sym_CARET] = ACTIONS(55),
    [aux_sym_postIntersection_token1] = ACTIONS(55),
  },
  [13] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_commentLine] = ACTIONS(57),
    [anon_sym_LBRACE_DASH] = ACTIONS(57),
    [sym_sym] = ACTIONS(57),
    [sym_nat] = ACTIONS(57),
    [sym_levelT] = ACTIONS(57),
    [anon_sym_POUNDU] = ACTIONS(57),
    [anon_sym_AT] = ACTIONS(57),
    [anon_sym_SEMI] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
    [sym_erased] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_SLASH_BSLASH] = ACTIONS(57),
    [anon_sym_COLON_GT] = ACTIONS(57),
    [anon_sym_CARET] = ACTIONS(57),
    [aux_sym_postIntersection_token1] = ACTIONS(57),
  },
  [14] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(59),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(59),
    [anon_sym_SLASH_BSLASH] = ACTIONS(59),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [15] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_SLASH_BSLASH] = ACTIONS(63),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [16] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [17] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(67),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [18] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [19] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(71),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [20] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [21] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [22] = {
    [sym__comment] = STATE(12),
    [sym_commentBlock] = STATE(12),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_erasedLambda] = STATE(11),
    [sym_intersectionT] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opIntersection] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__baseExpr] = STATE(11),
    [sym__preComments] = STATE(11),
    [sym__postComments] = STATE(11),
    [sym_postIntersection] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_commentLine] = ACTIONS(25),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(27),
    [sym_nat] = ACTIONS(27),
    [sym_levelT] = ACTIONS(27),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_COLON_GT] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(35),
  },
  [23] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(3),
    [sym_named] = STATE(3),
    [sym_bracket] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym_erasedLambda] = STATE(3),
    [sym_intersectionT] = STATE(3),
    [sym_opTyped] = STATE(3),
    [sym_opIntersection] = STATE(3),
    [sym_opApp] = STATE(3),
    [sym__baseExpr] = STATE(3),
    [sym__preComments] = STATE(3),
    [sym__postComments] = STATE(3),
    [sym_postIntersection] = STATE(3),
    [sym__expr] = STATE(3),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(79),
    [sym_nat] = ACTIONS(79),
    [sym_levelT] = ACTIONS(79),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [24] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(7),
    [sym_named] = STATE(7),
    [sym_bracket] = STATE(7),
    [sym_lambda] = STATE(7),
    [sym_erasedLambda] = STATE(7),
    [sym_intersectionT] = STATE(7),
    [sym_opTyped] = STATE(7),
    [sym_opIntersection] = STATE(7),
    [sym_opApp] = STATE(7),
    [sym__baseExpr] = STATE(7),
    [sym__preComments] = STATE(7),
    [sym__postComments] = STATE(7),
    [sym_postIntersection] = STATE(7),
    [sym__expr] = STATE(7),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(81),
    [sym_nat] = ACTIONS(81),
    [sym_levelT] = ACTIONS(81),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [25] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(6),
    [sym_named] = STATE(6),
    [sym_bracket] = STATE(6),
    [sym_lambda] = STATE(6),
    [sym_erasedLambda] = STATE(6),
    [sym_intersectionT] = STATE(6),
    [sym_opTyped] = STATE(6),
    [sym_opIntersection] = STATE(6),
    [sym_opApp] = STATE(6),
    [sym__baseExpr] = STATE(6),
    [sym__preComments] = STATE(6),
    [sym__postComments] = STATE(6),
    [sym_postIntersection] = STATE(6),
    [sym__expr] = STATE(6),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(83),
    [sym_nat] = ACTIONS(83),
    [sym_levelT] = ACTIONS(83),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [26] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(4),
    [sym_named] = STATE(4),
    [sym_bracket] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_erasedLambda] = STATE(4),
    [sym_intersectionT] = STATE(4),
    [sym_opTyped] = STATE(4),
    [sym_opIntersection] = STATE(4),
    [sym_opApp] = STATE(4),
    [sym__baseExpr] = STATE(4),
    [sym__preComments] = STATE(4),
    [sym__postComments] = STATE(4),
    [sym_postIntersection] = STATE(4),
    [sym__expr] = STATE(4),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(85),
    [sym_nat] = ACTIONS(85),
    [sym_levelT] = ACTIONS(85),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [27] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(22),
    [sym_named] = STATE(22),
    [sym_bracket] = STATE(22),
    [sym_lambda] = STATE(22),
    [sym_erasedLambda] = STATE(22),
    [sym_intersectionT] = STATE(22),
    [sym_opTyped] = STATE(22),
    [sym_opIntersection] = STATE(22),
    [sym_opApp] = STATE(22),
    [sym__baseExpr] = STATE(22),
    [sym__preComments] = STATE(22),
    [sym__postComments] = STATE(22),
    [sym_postIntersection] = STATE(22),
    [sym__expr] = STATE(22),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(87),
    [sym_nat] = ACTIONS(87),
    [sym_levelT] = ACTIONS(87),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [28] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(18),
    [sym_named] = STATE(18),
    [sym_bracket] = STATE(18),
    [sym_lambda] = STATE(18),
    [sym_erasedLambda] = STATE(18),
    [sym_intersectionT] = STATE(18),
    [sym_opTyped] = STATE(18),
    [sym_opIntersection] = STATE(18),
    [sym_opApp] = STATE(18),
    [sym__baseExpr] = STATE(18),
    [sym__preComments] = STATE(18),
    [sym__postComments] = STATE(18),
    [sym_postIntersection] = STATE(18),
    [sym__expr] = STATE(18),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(89),
    [sym_nat] = ACTIONS(89),
    [sym_levelT] = ACTIONS(89),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [29] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(15),
    [sym_named] = STATE(15),
    [sym_bracket] = STATE(15),
    [sym_lambda] = STATE(15),
    [sym_erasedLambda] = STATE(15),
    [sym_intersectionT] = STATE(15),
    [sym_opTyped] = STATE(15),
    [sym_opIntersection] = STATE(15),
    [sym_opApp] = STATE(15),
    [sym__baseExpr] = STATE(15),
    [sym__preComments] = STATE(15),
    [sym__postComments] = STATE(15),
    [sym_postIntersection] = STATE(15),
    [sym__expr] = STATE(15),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(91),
    [sym_nat] = ACTIONS(91),
    [sym_levelT] = ACTIONS(91),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [30] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(8),
    [sym_named] = STATE(8),
    [sym_bracket] = STATE(8),
    [sym_lambda] = STATE(8),
    [sym_erasedLambda] = STATE(8),
    [sym_intersectionT] = STATE(8),
    [sym_opTyped] = STATE(8),
    [sym_opIntersection] = STATE(8),
    [sym_opApp] = STATE(8),
    [sym__baseExpr] = STATE(8),
    [sym__preComments] = STATE(8),
    [sym__postComments] = STATE(8),
    [sym_postIntersection] = STATE(8),
    [sym__expr] = STATE(8),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(93),
    [sym_nat] = ACTIONS(93),
    [sym_levelT] = ACTIONS(93),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [31] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(17),
    [sym_named] = STATE(17),
    [sym_bracket] = STATE(17),
    [sym_lambda] = STATE(17),
    [sym_erasedLambda] = STATE(17),
    [sym_intersectionT] = STATE(17),
    [sym_opTyped] = STATE(17),
    [sym_opIntersection] = STATE(17),
    [sym_opApp] = STATE(17),
    [sym__baseExpr] = STATE(17),
    [sym__preComments] = STATE(17),
    [sym__postComments] = STATE(17),
    [sym_postIntersection] = STATE(17),
    [sym__expr] = STATE(17),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(95),
    [sym_nat] = ACTIONS(95),
    [sym_levelT] = ACTIONS(95),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [32] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(14),
    [sym_named] = STATE(14),
    [sym_bracket] = STATE(14),
    [sym_lambda] = STATE(14),
    [sym_erasedLambda] = STATE(14),
    [sym_intersectionT] = STATE(14),
    [sym_opTyped] = STATE(14),
    [sym_opIntersection] = STATE(14),
    [sym_opApp] = STATE(14),
    [sym__baseExpr] = STATE(14),
    [sym__preComments] = STATE(14),
    [sym__postComments] = STATE(14),
    [sym_postIntersection] = STATE(14),
    [sym__expr] = STATE(14),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(97),
    [sym_nat] = ACTIONS(97),
    [sym_levelT] = ACTIONS(97),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [33] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(21),
    [sym_named] = STATE(21),
    [sym_bracket] = STATE(21),
    [sym_lambda] = STATE(21),
    [sym_erasedLambda] = STATE(21),
    [sym_intersectionT] = STATE(21),
    [sym_opTyped] = STATE(21),
    [sym_opIntersection] = STATE(21),
    [sym_opApp] = STATE(21),
    [sym__baseExpr] = STATE(21),
    [sym__preComments] = STATE(21),
    [sym__postComments] = STATE(21),
    [sym_postIntersection] = STATE(21),
    [sym__expr] = STATE(21),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(99),
    [sym_nat] = ACTIONS(101),
    [sym_levelT] = ACTIONS(101),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [34] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(20),
    [sym_named] = STATE(20),
    [sym_bracket] = STATE(20),
    [sym_lambda] = STATE(20),
    [sym_erasedLambda] = STATE(20),
    [sym_intersectionT] = STATE(20),
    [sym_opTyped] = STATE(20),
    [sym_opIntersection] = STATE(20),
    [sym_opApp] = STATE(20),
    [sym__baseExpr] = STATE(20),
    [sym__preComments] = STATE(20),
    [sym__postComments] = STATE(20),
    [sym_postIntersection] = STATE(20),
    [sym__expr] = STATE(20),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(103),
    [sym_nat] = ACTIONS(105),
    [sym_levelT] = ACTIONS(105),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [35] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(19),
    [sym_named] = STATE(19),
    [sym_bracket] = STATE(19),
    [sym_lambda] = STATE(19),
    [sym_erasedLambda] = STATE(19),
    [sym_intersectionT] = STATE(19),
    [sym_opTyped] = STATE(19),
    [sym_opIntersection] = STATE(19),
    [sym_opApp] = STATE(19),
    [sym__baseExpr] = STATE(19),
    [sym__preComments] = STATE(19),
    [sym__postComments] = STATE(19),
    [sym_postIntersection] = STATE(19),
    [sym__expr] = STATE(19),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(107),
    [sym_nat] = ACTIONS(107),
    [sym_levelT] = ACTIONS(107),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
  [36] = {
    [sym__comment] = STATE(10),
    [sym_commentBlock] = STATE(10),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_erasedLambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(109),
    [sym_nat] = ACTIONS(109),
    [sym_levelT] = ACTIONS(109),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(113), 1,
      anon_sym_PLUS,
    ACTIONS(111), 21,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [27] = 3,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_levels_repeat1,
    ACTIONS(115), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [56] = 3,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_levels_repeat1,
    ACTIONS(119), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [85] = 3,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_levels_repeat1,
    ACTIONS(121), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [114] = 1,
    ACTIONS(126), 21,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [138] = 1,
    ACTIONS(121), 21,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [162] = 1,
    ACTIONS(128), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [185] = 1,
    ACTIONS(130), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [208] = 1,
    ACTIONS(132), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [231] = 1,
    ACTIONS(134), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [254] = 1,
    ACTIONS(136), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [277] = 1,
    ACTIONS(138), 20,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [300] = 2,
    ACTIONS(142), 1,
      anon_sym_COLON,
    ACTIONS(140), 15,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_LBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [321] = 2,
    ACTIONS(144), 1,
      anon_sym_COLON,
    ACTIONS(140), 15,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_LBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [342] = 5,
    ACTIONS(148), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(150), 1,
      anon_sym_DASH_RBRACE,
    STATE(47), 1,
      sym__endComment,
    ACTIONS(146), 2,
      sym_commentLine,
      aux_sym__endComment_token1,
    STATE(52), 2,
      sym__comment,
      sym_commentBlock,
  [360] = 5,
    ACTIONS(148), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(152), 1,
      anon_sym_DASH_RBRACE,
    STATE(45), 1,
      sym__endComment,
    ACTIONS(146), 2,
      sym_commentLine,
      aux_sym__endComment_token1,
    STATE(52), 2,
      sym__comment,
      sym_commentBlock,
  [378] = 5,
    ACTIONS(148), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(156), 1,
      anon_sym_DASH_RBRACE,
    STATE(58), 1,
      sym__endComment,
    ACTIONS(154), 2,
      sym_commentLine,
      aux_sym__endComment_token1,
    STATE(53), 2,
      sym__comment,
      sym_commentBlock,
  [396] = 5,
    ACTIONS(148), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(158), 1,
      anon_sym_DASH_RBRACE,
    STATE(57), 1,
      sym__endComment,
    ACTIONS(154), 2,
      sym_commentLine,
      aux_sym__endComment_token1,
    STATE(53), 2,
      sym__comment,
      sym_commentBlock,
  [414] = 4,
    ACTIONS(160), 1,
      sym_sym,
    ACTIONS(162), 1,
      sym_nat,
    STATE(43), 1,
      sym_levels,
    STATE(38), 2,
      sym__level,
      sym_levelAdd,
  [428] = 3,
    ACTIONS(160), 1,
      sym_sym,
    ACTIONS(164), 1,
      sym_nat,
    STATE(42), 2,
      sym__level,
      sym_levelAdd,
  [439] = 1,
    ACTIONS(166), 4,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      anon_sym_DASH_RBRACE,
      aux_sym__endComment_token1,
  [446] = 1,
    ACTIONS(168), 4,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      anon_sym_DASH_RBRACE,
      aux_sym__endComment_token1,
  [453] = 1,
    ACTIONS(170), 1,
      sym_nat,
  [457] = 1,
    ACTIONS(172), 1,
      anon_sym_EQ,
  [461] = 1,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
  [465] = 1,
    ACTIONS(176), 1,
      sym_sym,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(37)] = 0,
  [SMALL_STATE(38)] = 27,
  [SMALL_STATE(39)] = 56,
  [SMALL_STATE(40)] = 85,
  [SMALL_STATE(41)] = 114,
  [SMALL_STATE(42)] = 138,
  [SMALL_STATE(43)] = 162,
  [SMALL_STATE(44)] = 185,
  [SMALL_STATE(45)] = 208,
  [SMALL_STATE(46)] = 231,
  [SMALL_STATE(47)] = 254,
  [SMALL_STATE(48)] = 277,
  [SMALL_STATE(49)] = 300,
  [SMALL_STATE(50)] = 321,
  [SMALL_STATE(51)] = 342,
  [SMALL_STATE(52)] = 360,
  [SMALL_STATE(53)] = 378,
  [SMALL_STATE(54)] = 396,
  [SMALL_STATE(55)] = 414,
  [SMALL_STATE(56)] = 428,
  [SMALL_STATE(57)] = 439,
  [SMALL_STATE(58)] = 446,
  [SMALL_STATE(59)] = 453,
  [SMALL_STATE(60)] = 457,
  [SMALL_STATE(61)] = 461,
  [SMALL_STATE(62)] = 465,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named, 5, 0, 2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erasedLambda, 6, 0, 4),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opIntersection, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 6, 0, 4),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opTyped, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opApp, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4, 0, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named, 6, 0, 3),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opApp, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__postComments, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__preComments, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erasedLambda, 4, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__level, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_levels, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_levels, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_levels_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_levels_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_levelAdd, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_universe, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__endComment, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postIntersection, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commentBlock, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intersectionT, 7, 0, 5),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__baseExpr, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commentBlock, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__endComment, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [174] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_eriun(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
