#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 27
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 6

enum ts_symbol_identifiers {
  sym_commentLine = 1,
  anon_sym_LBRACE_DASH = 2,
  anon_sym_DASH_RBRACE = 3,
  aux_sym__endComment_token1 = 4,
  sym_sym = 5,
  sym_nat = 6,
  sym_levelT = 7,
  anon_sym_COMMA = 8,
  anon_sym_PLUS = 9,
  anon_sym_POUNDU = 10,
  anon_sym_AT = 11,
  anon_sym_EQ = 12,
  anon_sym_SEMI = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  sym_erased = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COLON = 18,
  anon_sym_RPAREN = 19,
  anon_sym_DASH_GT = 20,
  anon_sym_SLASH_BSLASH = 21,
  anon_sym_COLON_GT = 22,
  anon_sym_CARET = 23,
  aux_sym_postIntersection_token1 = 24,
  sym_expr = 25,
  sym__comment = 26,
  sym_commentBlock = 27,
  sym__endComment = 28,
  sym_levels = 29,
  sym__level = 30,
  sym_levelAdd = 31,
  sym_universe = 32,
  sym_named = 33,
  sym_bracket = 34,
  sym_lambda = 35,
  sym_intersectionT = 36,
  sym_opTyped = 37,
  sym_opIntersection = 38,
  sym_opApp = 39,
  sym__baseExpr = 40,
  sym__preComments = 41,
  sym__postComments = 42,
  sym_postIntersection = 43,
  sym__expr = 44,
  aux_sym_levels_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_commentLine] = "commentLine",
  [anon_sym_LBRACE_DASH] = "{- ",
  [anon_sym_DASH_RBRACE] = " -}",
  [aux_sym__endComment_token1] = "_endComment_token1",
  [sym_sym] = "sym",
  [sym_nat] = "nat",
  [sym_levelT] = "levelT",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_POUNDU] = "#U",
  [anon_sym_AT] = "@",
  [anon_sym_EQ] = " = ",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_erased] = "erased",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_SLASH_BSLASH] = "/\\",
  [anon_sym_COLON_GT] = ":>",
  [anon_sym_CARET] = "^",
  [aux_sym_postIntersection_token1] = "postIntersection_token1",
  [sym_expr] = "expr",
  [sym__comment] = "_comment",
  [sym_commentBlock] = "commentBlock",
  [sym__endComment] = "_endComment",
  [sym_levels] = "levels",
  [sym__level] = "_level",
  [sym_levelAdd] = "levelAdd",
  [sym_universe] = "universe",
  [sym_named] = "named",
  [sym_bracket] = "bracket",
  [sym_lambda] = "lambda",
  [sym_intersectionT] = "intersectionT",
  [sym_opTyped] = "opTyped",
  [sym_opIntersection] = "opIntersection",
  [sym_opApp] = "opApp",
  [sym__baseExpr] = "_baseExpr",
  [sym__preComments] = "_preComments",
  [sym__postComments] = "_postComments",
  [sym_postIntersection] = "postIntersection",
  [sym__expr] = "_expr",
  [aux_sym_levels_repeat1] = "levels_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_commentLine] = sym_commentLine,
  [anon_sym_LBRACE_DASH] = anon_sym_LBRACE_DASH,
  [anon_sym_DASH_RBRACE] = anon_sym_DASH_RBRACE,
  [aux_sym__endComment_token1] = aux_sym__endComment_token1,
  [sym_sym] = sym_sym,
  [sym_nat] = sym_nat,
  [sym_levelT] = sym_levelT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_POUNDU] = anon_sym_POUNDU,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_erased] = sym_erased,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_SLASH_BSLASH] = anon_sym_SLASH_BSLASH,
  [anon_sym_COLON_GT] = anon_sym_COLON_GT,
  [anon_sym_CARET] = anon_sym_CARET,
  [aux_sym_postIntersection_token1] = aux_sym_postIntersection_token1,
  [sym_expr] = sym_expr,
  [sym__comment] = sym__comment,
  [sym_commentBlock] = sym_commentBlock,
  [sym__endComment] = sym__endComment,
  [sym_levels] = sym_levels,
  [sym__level] = sym__level,
  [sym_levelAdd] = sym_levelAdd,
  [sym_universe] = sym_universe,
  [sym_named] = sym_named,
  [sym_bracket] = sym_bracket,
  [sym_lambda] = sym_lambda,
  [sym_intersectionT] = sym_intersectionT,
  [sym_opTyped] = sym_opTyped,
  [sym_opIntersection] = sym_opIntersection,
  [sym_opApp] = sym_opApp,
  [sym__baseExpr] = sym__baseExpr,
  [sym__preComments] = sym__preComments,
  [sym__postComments] = sym__postComments,
  [sym_postIntersection] = sym_postIntersection,
  [sym__expr] = sym__expr,
  [aux_sym_levels_repeat1] = aux_sym_levels_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_commentLine] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__endComment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_sym] = {
    .visible = true,
    .named = true,
  },
  [sym_nat] = {
    .visible = true,
    .named = true,
  },
  [sym_levelT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDU] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_erased] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_postIntersection_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_commentBlock] = {
    .visible = true,
    .named = true,
  },
  [sym__endComment] = {
    .visible = false,
    .named = true,
  },
  [sym_levels] = {
    .visible = true,
    .named = true,
  },
  [sym__level] = {
    .visible = false,
    .named = true,
  },
  [sym_levelAdd] = {
    .visible = true,
    .named = true,
  },
  [sym_universe] = {
    .visible = true,
    .named = true,
  },
  [sym_named] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_intersectionT] = {
    .visible = true,
    .named = true,
  },
  [sym_opTyped] = {
    .visible = true,
    .named = true,
  },
  [sym_opIntersection] = {
    .visible = true,
    .named = true,
  },
  [sym_opApp] = {
    .visible = true,
    .named = true,
  },
  [sym__baseExpr] = {
    .visible = false,
    .named = true,
  },
  [sym__preComments] = {
    .visible = false,
    .named = true,
  },
  [sym__postComments] = {
    .visible = false,
    .named = true,
  },
  [sym_postIntersection] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_levels_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_erasure = 2,
  field_name = 3,
  field_rest = 4,
  field_type = 5,
  field_type1 = 6,
  field_type2 = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_erasure] = "erasure",
  [field_name] = "name",
  [field_rest] = "rest",
  [field_type] = "type",
  [field_type1] = "type1",
  [field_type2] = "type2",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 3},
  [5] = {.index = 11, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 3},
    {field_name, 1},
  [2] =
    {field_body, 3},
    {field_name, 1},
    {field_rest, 5},
  [5] =
    {field_body, 6},
    {field_name, 1},
    {field_type, 3},
  [8] =
    {field_name, 1},
    {field_type1, 3},
    {field_type2, 5},
  [11] =
    {field_body, 7},
    {field_erasure, 5},
    {field_name, 1},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 39,
  [43] = 43,
  [44] = 35,
  [45] = 45,
  [46] = 37,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        ' ', 2,
        '#', 13,
        '\'', 38,
        '(', 39,
        ')', 42,
        '+', 31,
        ',', 30,
        '-', 8,
        '.', 15,
        '/', 14,
        ':', 41,
        ';', 35,
        '@', 33,
        '[', 36,
        ']', 37,
        '^', 46,
        '{', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 2,
        '#', 13,
        '\'', 38,
        '(', 39,
        ')', 42,
        '+', 31,
        ',', 30,
        '-', 8,
        '.', 15,
        '/', 14,
        ':', 41,
        ';', 35,
        '@', 33,
        '[', 36,
        ']', 37,
        '^', 46,
        '{', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 2,
        '#', 13,
        '\'', 38,
        '(', 39,
        ')', 42,
        '+', 31,
        ',', 30,
        '-', 9,
        '.', 15,
        '/', 14,
        ':', 41,
        ';', 35,
        '=', 3,
        '@', 33,
        '[', 36,
        ']', 37,
        '^', 46,
        '{', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(22);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '>') ADVANCE(43);
      if (lookahead == '}') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 13:
      if (lookahead == 'L') ADVANCE(29);
      if (lookahead == 'U') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == '\\') ADVANCE(44);
      END_STATE();
    case 15:
      if (lookahead == '1' ||
          lookahead == '2') ADVANCE(47);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '#', 13,
        '\'', 38,
        '(', 39,
        ')', 42,
        '+', 31,
        ',', 30,
        '-', 7,
        '.', 15,
        '/', 14,
        ':', 12,
        ';', 35,
        '@', 33,
        '[', 36,
        ']', 37,
        '^', 46,
        '{', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_commentLine);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE_DASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(22);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(22);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '}') ADVANCE(20);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__endComment_token1);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_sym);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_nat);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_levelT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_POUNDU);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_erased);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH_BSLASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_postIntersection_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 16},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 16},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_commentLine] = ACTIONS(1),
    [anon_sym_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_DASH_RBRACE] = ACTIONS(1),
    [sym_sym] = ACTIONS(1),
    [sym_nat] = ACTIONS(1),
    [sym_levelT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_POUNDU] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_erased] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_SLASH_BSLASH] = ACTIONS(1),
    [anon_sym_COLON_GT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [aux_sym_postIntersection_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_expr] = STATE(49),
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(14),
    [sym_named] = STATE(14),
    [sym_bracket] = STATE(14),
    [sym_lambda] = STATE(14),
    [sym_intersectionT] = STATE(14),
    [sym_opTyped] = STATE(14),
    [sym_opIntersection] = STATE(14),
    [sym_opApp] = STATE(14),
    [sym__baseExpr] = STATE(14),
    [sym__preComments] = STATE(14),
    [sym__postComments] = STATE(14),
    [sym_postIntersection] = STATE(14),
    [sym__expr] = STATE(14),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(7),
    [sym_nat] = ACTIONS(7),
    [sym_levelT] = ACTIONS(7),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [2] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_commentLine] = ACTIONS(17),
    [anon_sym_LBRACE_DASH] = ACTIONS(17),
    [sym_sym] = ACTIONS(17),
    [sym_nat] = ACTIONS(17),
    [sym_levelT] = ACTIONS(17),
    [anon_sym_POUNDU] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(17),
    [sym_erased] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(17),
    [anon_sym_SLASH_BSLASH] = ACTIONS(17),
    [anon_sym_COLON_GT] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [aux_sym_postIntersection_token1] = ACTIONS(17),
  },
  [3] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(19),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_SLASH_BSLASH] = ACTIONS(19),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [4] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(33),
    [sym_nat] = ACTIONS(33),
    [sym_levelT] = ACTIONS(33),
    [anon_sym_POUNDU] = ACTIONS(33),
    [anon_sym_AT] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(33),
    [sym_erased] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(33),
    [anon_sym_SLASH_BSLASH] = ACTIONS(33),
    [anon_sym_COLON_GT] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(33),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [5] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(35),
    [sym_nat] = ACTIONS(35),
    [sym_levelT] = ACTIONS(35),
    [anon_sym_POUNDU] = ACTIONS(35),
    [anon_sym_AT] = ACTIONS(35),
    [anon_sym_SEMI] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(35),
    [sym_erased] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_SLASH_BSLASH] = ACTIONS(35),
    [anon_sym_COLON_GT] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(35),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [6] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(37),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(37),
    [anon_sym_SLASH_BSLASH] = ACTIONS(37),
    [anon_sym_COLON_GT] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [7] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_SLASH_BSLASH] = ACTIONS(39),
    [anon_sym_COLON_GT] = ACTIONS(39),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [8] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(2),
    [sym_named] = STATE(2),
    [sym_bracket] = STATE(2),
    [sym_lambda] = STATE(2),
    [sym_intersectionT] = STATE(2),
    [sym_opTyped] = STATE(2),
    [sym_opIntersection] = STATE(2),
    [sym_opApp] = STATE(2),
    [sym__baseExpr] = STATE(2),
    [sym__preComments] = STATE(2),
    [sym__postComments] = STATE(2),
    [sym_postIntersection] = STATE(2),
    [sym__expr] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(43),
    [sym_nat] = ACTIONS(43),
    [sym_levelT] = ACTIONS(43),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(41),
    [sym_erased] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_SLASH_BSLASH] = ACTIONS(41),
    [anon_sym_COLON_GT] = ACTIONS(41),
    [anon_sym_CARET] = ACTIONS(41),
    [aux_sym_postIntersection_token1] = ACTIONS(41),
  },
  [9] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(45),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_SLASH_BSLASH] = ACTIONS(45),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [10] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_commentLine] = ACTIONS(47),
    [anon_sym_LBRACE_DASH] = ACTIONS(47),
    [sym_sym] = ACTIONS(47),
    [sym_nat] = ACTIONS(47),
    [sym_levelT] = ACTIONS(47),
    [anon_sym_POUNDU] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(47),
    [anon_sym_RBRACK] = ACTIONS(47),
    [sym_erased] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_SLASH_BSLASH] = ACTIONS(47),
    [anon_sym_COLON_GT] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(47),
    [aux_sym_postIntersection_token1] = ACTIONS(47),
  },
  [11] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(2),
    [sym_named] = STATE(2),
    [sym_bracket] = STATE(2),
    [sym_lambda] = STATE(2),
    [sym_intersectionT] = STATE(2),
    [sym_opTyped] = STATE(2),
    [sym_opIntersection] = STATE(2),
    [sym_opApp] = STATE(2),
    [sym__baseExpr] = STATE(2),
    [sym__preComments] = STATE(2),
    [sym__postComments] = STATE(2),
    [sym_postIntersection] = STATE(2),
    [sym__expr] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(43),
    [sym_nat] = ACTIONS(43),
    [sym_levelT] = ACTIONS(43),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(49),
    [sym_erased] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_SLASH_BSLASH] = ACTIONS(49),
    [anon_sym_COLON_GT] = ACTIONS(49),
    [anon_sym_CARET] = ACTIONS(49),
    [aux_sym_postIntersection_token1] = ACTIONS(49),
  },
  [12] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(10),
    [sym_named] = STATE(10),
    [sym_bracket] = STATE(10),
    [sym_lambda] = STATE(10),
    [sym_intersectionT] = STATE(10),
    [sym_opTyped] = STATE(10),
    [sym_opIntersection] = STATE(10),
    [sym_opApp] = STATE(10),
    [sym__baseExpr] = STATE(10),
    [sym__preComments] = STATE(10),
    [sym__postComments] = STATE(10),
    [sym_postIntersection] = STATE(10),
    [sym__expr] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(53),
    [sym_nat] = ACTIONS(53),
    [sym_levelT] = ACTIONS(53),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(51),
    [sym_erased] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(51),
    [anon_sym_SLASH_BSLASH] = ACTIONS(51),
    [anon_sym_COLON_GT] = ACTIONS(51),
    [anon_sym_CARET] = ACTIONS(51),
    [aux_sym_postIntersection_token1] = ACTIONS(51),
  },
  [13] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(55),
    [anon_sym_SLASH_BSLASH] = ACTIONS(57),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [14] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [15] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(61),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [16] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(63),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [17] = {
    [sym__comment] = STATE(11),
    [sym_commentBlock] = STATE(11),
    [sym_universe] = STATE(5),
    [sym_named] = STATE(5),
    [sym_bracket] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym_intersectionT] = STATE(5),
    [sym_opTyped] = STATE(5),
    [sym_opIntersection] = STATE(5),
    [sym_opApp] = STATE(5),
    [sym__baseExpr] = STATE(5),
    [sym__preComments] = STATE(5),
    [sym__postComments] = STATE(5),
    [sym_postIntersection] = STATE(5),
    [sym__expr] = STATE(5),
    [sym_commentLine] = ACTIONS(21),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_levelT] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(29),
    [aux_sym_postIntersection_token1] = ACTIONS(31),
  },
  [18] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(9),
    [sym_named] = STATE(9),
    [sym_bracket] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_intersectionT] = STATE(9),
    [sym_opTyped] = STATE(9),
    [sym_opIntersection] = STATE(9),
    [sym_opApp] = STATE(9),
    [sym__baseExpr] = STATE(9),
    [sym__preComments] = STATE(9),
    [sym__postComments] = STATE(9),
    [sym_postIntersection] = STATE(9),
    [sym__expr] = STATE(9),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(67),
    [sym_nat] = ACTIONS(67),
    [sym_levelT] = ACTIONS(67),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [19] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(17),
    [sym_named] = STATE(17),
    [sym_bracket] = STATE(17),
    [sym_lambda] = STATE(17),
    [sym_intersectionT] = STATE(17),
    [sym_opTyped] = STATE(17),
    [sym_opIntersection] = STATE(17),
    [sym_opApp] = STATE(17),
    [sym__baseExpr] = STATE(17),
    [sym__preComments] = STATE(17),
    [sym__postComments] = STATE(17),
    [sym_postIntersection] = STATE(17),
    [sym__expr] = STATE(17),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(69),
    [sym_nat] = ACTIONS(69),
    [sym_levelT] = ACTIONS(69),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [20] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(13),
    [sym_named] = STATE(13),
    [sym_bracket] = STATE(13),
    [sym_lambda] = STATE(13),
    [sym_intersectionT] = STATE(13),
    [sym_opTyped] = STATE(13),
    [sym_opIntersection] = STATE(13),
    [sym_opApp] = STATE(13),
    [sym__baseExpr] = STATE(13),
    [sym__preComments] = STATE(13),
    [sym__postComments] = STATE(13),
    [sym_postIntersection] = STATE(13),
    [sym__expr] = STATE(13),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(71),
    [sym_nat] = ACTIONS(71),
    [sym_levelT] = ACTIONS(71),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [21] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(4),
    [sym_named] = STATE(4),
    [sym_bracket] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_intersectionT] = STATE(4),
    [sym_opTyped] = STATE(4),
    [sym_opIntersection] = STATE(4),
    [sym_opApp] = STATE(4),
    [sym__baseExpr] = STATE(4),
    [sym__preComments] = STATE(4),
    [sym__postComments] = STATE(4),
    [sym_postIntersection] = STATE(4),
    [sym__expr] = STATE(4),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(73),
    [sym_nat] = ACTIONS(73),
    [sym_levelT] = ACTIONS(73),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [22] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(6),
    [sym_named] = STATE(6),
    [sym_bracket] = STATE(6),
    [sym_lambda] = STATE(6),
    [sym_intersectionT] = STATE(6),
    [sym_opTyped] = STATE(6),
    [sym_opIntersection] = STATE(6),
    [sym_opApp] = STATE(6),
    [sym__baseExpr] = STATE(6),
    [sym__preComments] = STATE(6),
    [sym__postComments] = STATE(6),
    [sym_postIntersection] = STATE(6),
    [sym__expr] = STATE(6),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(75),
    [sym_nat] = ACTIONS(75),
    [sym_levelT] = ACTIONS(75),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [23] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(7),
    [sym_named] = STATE(7),
    [sym_bracket] = STATE(7),
    [sym_lambda] = STATE(7),
    [sym_intersectionT] = STATE(7),
    [sym_opTyped] = STATE(7),
    [sym_opIntersection] = STATE(7),
    [sym_opApp] = STATE(7),
    [sym__baseExpr] = STATE(7),
    [sym__preComments] = STATE(7),
    [sym__postComments] = STATE(7),
    [sym_postIntersection] = STATE(7),
    [sym__expr] = STATE(7),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(77),
    [sym_nat] = ACTIONS(77),
    [sym_levelT] = ACTIONS(77),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [24] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(3),
    [sym_named] = STATE(3),
    [sym_bracket] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym_intersectionT] = STATE(3),
    [sym_opTyped] = STATE(3),
    [sym_opIntersection] = STATE(3),
    [sym_opApp] = STATE(3),
    [sym__baseExpr] = STATE(3),
    [sym__preComments] = STATE(3),
    [sym__postComments] = STATE(3),
    [sym_postIntersection] = STATE(3),
    [sym__expr] = STATE(3),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(79),
    [sym_nat] = ACTIONS(79),
    [sym_levelT] = ACTIONS(79),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [25] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(15),
    [sym_named] = STATE(15),
    [sym_bracket] = STATE(15),
    [sym_lambda] = STATE(15),
    [sym_intersectionT] = STATE(15),
    [sym_opTyped] = STATE(15),
    [sym_opIntersection] = STATE(15),
    [sym_opApp] = STATE(15),
    [sym__baseExpr] = STATE(15),
    [sym__preComments] = STATE(15),
    [sym__postComments] = STATE(15),
    [sym_postIntersection] = STATE(15),
    [sym__expr] = STATE(15),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(81),
    [sym_nat] = ACTIONS(81),
    [sym_levelT] = ACTIONS(81),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [26] = {
    [sym__comment] = STATE(8),
    [sym_commentBlock] = STATE(8),
    [sym_universe] = STATE(16),
    [sym_named] = STATE(16),
    [sym_bracket] = STATE(16),
    [sym_lambda] = STATE(16),
    [sym_intersectionT] = STATE(16),
    [sym_opTyped] = STATE(16),
    [sym_opIntersection] = STATE(16),
    [sym_opApp] = STATE(16),
    [sym__baseExpr] = STATE(16),
    [sym__preComments] = STATE(16),
    [sym__postComments] = STATE(16),
    [sym_postIntersection] = STATE(16),
    [sym__expr] = STATE(16),
    [sym_commentLine] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(83),
    [sym_nat] = ACTIONS(83),
    [sym_levelT] = ACTIONS(83),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym_levels_repeat1,
    ACTIONS(85), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [27] = 2,
    ACTIONS(91), 1,
      anon_sym_PLUS,
    ACTIONS(89), 19,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [52] = 3,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_levels_repeat1,
    ACTIONS(93), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [79] = 3,
    ACTIONS(97), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_levels_repeat1,
    ACTIONS(95), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [106] = 1,
    ACTIONS(100), 19,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [128] = 1,
    ACTIONS(95), 19,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [150] = 1,
    ACTIONS(102), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [171] = 1,
    ACTIONS(104), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [192] = 1,
    ACTIONS(106), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [213] = 1,
    ACTIONS(108), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [234] = 1,
    ACTIONS(110), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [255] = 1,
    ACTIONS(112), 18,
      ts_builtin_sym_end,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_levelT,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SLASH_BSLASH,
      anon_sym_COLON_GT,
      anon_sym_CARET,
      aux_sym_postIntersection_token1,
  [276] = 5,
    ACTIONS(116), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(118), 1,
      anon_sym_DASH_RBRACE,
    STATE(44), 1,
      sym__endComment,
    ACTIONS(114), 2,
      sym_commentLine,
      aux_sym__endComment_token1,
    STATE(39), 2,
      sym__comment,
      sym_commentBlock,
  [294] = 5,
    ACTIONS(116), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(120), 1,
      anon_sym_DASH_RBRACE,
    STATE(46), 1,
      sym__endComment,
    ACTIONS(114), 2,
      sym_commentLine,
      aux_sym__endComment_token1,
    STATE(39), 2,
      sym__comment,
      sym_commentBlock,
  [312] = 5,
    ACTIONS(116), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(124), 1,
      anon_sym_DASH_RBRACE,
    STATE(37), 1,
      sym__endComment,
    ACTIONS(122), 2,
      sym_commentLine,
      aux_sym__endComment_token1,
    STATE(42), 2,
      sym__comment,
      sym_commentBlock,
  [330] = 5,
    ACTIONS(116), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(126), 1,
      anon_sym_DASH_RBRACE,
    STATE(35), 1,
      sym__endComment,
    ACTIONS(122), 2,
      sym_commentLine,
      aux_sym__endComment_token1,
    STATE(42), 2,
      sym__comment,
      sym_commentBlock,
  [348] = 4,
    ACTIONS(128), 1,
      sym_sym,
    ACTIONS(130), 1,
      sym_nat,
    STATE(33), 1,
      sym_levels,
    STATE(27), 2,
      sym__level,
      sym_levelAdd,
  [362] = 1,
    ACTIONS(132), 4,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      anon_sym_DASH_RBRACE,
      aux_sym__endComment_token1,
  [369] = 3,
    ACTIONS(128), 1,
      sym_sym,
    ACTIONS(134), 1,
      sym_nat,
    STATE(32), 2,
      sym__level,
      sym_levelAdd,
  [380] = 1,
    ACTIONS(136), 4,
      sym_commentLine,
      anon_sym_LBRACE_DASH,
      anon_sym_DASH_RBRACE,
      aux_sym__endComment_token1,
  [387] = 2,
    ACTIONS(138), 1,
      sym_erased,
    ACTIONS(140), 1,
      anon_sym_DASH_GT,
  [394] = 1,
    ACTIONS(142), 1,
      anon_sym_EQ,
  [398] = 1,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
  [402] = 1,
    ACTIONS(146), 1,
      sym_sym,
  [406] = 1,
    ACTIONS(148), 1,
      sym_sym,
  [410] = 1,
    ACTIONS(150), 1,
      sym_nat,
  [414] = 1,
    ACTIONS(152), 1,
      anon_sym_DASH_GT,
  [418] = 1,
    ACTIONS(154), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(27)] = 0,
  [SMALL_STATE(28)] = 27,
  [SMALL_STATE(29)] = 52,
  [SMALL_STATE(30)] = 79,
  [SMALL_STATE(31)] = 106,
  [SMALL_STATE(32)] = 128,
  [SMALL_STATE(33)] = 150,
  [SMALL_STATE(34)] = 171,
  [SMALL_STATE(35)] = 192,
  [SMALL_STATE(36)] = 213,
  [SMALL_STATE(37)] = 234,
  [SMALL_STATE(38)] = 255,
  [SMALL_STATE(39)] = 276,
  [SMALL_STATE(40)] = 294,
  [SMALL_STATE(41)] = 312,
  [SMALL_STATE(42)] = 330,
  [SMALL_STATE(43)] = 348,
  [SMALL_STATE(44)] = 362,
  [SMALL_STATE(45)] = 369,
  [SMALL_STATE(46)] = 380,
  [SMALL_STATE(47)] = 387,
  [SMALL_STATE(48)] = 394,
  [SMALL_STATE(49)] = 398,
  [SMALL_STATE(50)] = 402,
  [SMALL_STATE(51)] = 406,
  [SMALL_STATE(52)] = 410,
  [SMALL_STATE(53)] = 414,
  [SMALL_STATE(54)] = 418,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__preComments, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 7, 0, 3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opApp, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opApp, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opTyped, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opIntersection, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 8, 0, 5),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named, 6, 0, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__postComments, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named, 5, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_levels, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__level, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_levels, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_levels_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_levels_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_levelAdd, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_universe, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postIntersection, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__endComment, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commentBlock, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intersectionT, 7, 0, 4),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__endComment, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commentBlock, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [144] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_eriun(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
