#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 23
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  sym_comment_line = 1,
  anon_sym_LBRACE_DASH = 2,
  anon_sym_DASH_RBRACE = 3,
  aux_sym__end_comment_token1 = 4,
  sym_sym = 5,
  sym_nat = 6,
  sym_level_t = 7,
  anon_sym_COMMA = 8,
  anon_sym_PLUS = 9,
  anon_sym_POUNDU = 10,
  anon_sym_AT = 11,
  anon_sym_EQ = 12,
  anon_sym_SEMI = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  sym_erased = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COLON = 18,
  anon_sym_RPAREN = 19,
  anon_sym_DASH_GT = 20,
  anon_sym_COLON_GT = 21,
  sym_expr = 22,
  sym__comment = 23,
  sym_comment_block = 24,
  sym__end_comment = 25,
  sym_levels = 26,
  sym__level = 27,
  sym_level_add = 28,
  sym_universe = 29,
  sym_named = 30,
  sym_bracket = 31,
  sym_lambda = 32,
  sym_opTyped = 33,
  sym_opApp = 34,
  sym__base_expr = 35,
  sym__per_comments = 36,
  sym__post_comments = 37,
  sym__expr = 38,
  aux_sym_levels_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment_line] = "comment_line",
  [anon_sym_LBRACE_DASH] = "{- ",
  [anon_sym_DASH_RBRACE] = " -}",
  [aux_sym__end_comment_token1] = "_end_comment_token1",
  [sym_sym] = "sym",
  [sym_nat] = "nat",
  [sym_level_t] = "level_t",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_POUNDU] = "#U",
  [anon_sym_AT] = "@",
  [anon_sym_EQ] = " = ",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_erased] = "erased",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COLON_GT] = ":>",
  [sym_expr] = "expr",
  [sym__comment] = "_comment",
  [sym_comment_block] = "comment_block",
  [sym__end_comment] = "_end_comment",
  [sym_levels] = "levels",
  [sym__level] = "_level",
  [sym_level_add] = "level_add",
  [sym_universe] = "universe",
  [sym_named] = "named",
  [sym_bracket] = "bracket",
  [sym_lambda] = "lambda",
  [sym_opTyped] = "opTyped",
  [sym_opApp] = "opApp",
  [sym__base_expr] = "_base_expr",
  [sym__per_comments] = "_per_comments",
  [sym__post_comments] = "_post_comments",
  [sym__expr] = "_expr",
  [aux_sym_levels_repeat1] = "levels_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment_line] = sym_comment_line,
  [anon_sym_LBRACE_DASH] = anon_sym_LBRACE_DASH,
  [anon_sym_DASH_RBRACE] = anon_sym_DASH_RBRACE,
  [aux_sym__end_comment_token1] = aux_sym__end_comment_token1,
  [sym_sym] = sym_sym,
  [sym_nat] = sym_nat,
  [sym_level_t] = sym_level_t,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_POUNDU] = anon_sym_POUNDU,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_erased] = sym_erased,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COLON_GT] = anon_sym_COLON_GT,
  [sym_expr] = sym_expr,
  [sym__comment] = sym__comment,
  [sym_comment_block] = sym_comment_block,
  [sym__end_comment] = sym__end_comment,
  [sym_levels] = sym_levels,
  [sym__level] = sym__level,
  [sym_level_add] = sym_level_add,
  [sym_universe] = sym_universe,
  [sym_named] = sym_named,
  [sym_bracket] = sym_bracket,
  [sym_lambda] = sym_lambda,
  [sym_opTyped] = sym_opTyped,
  [sym_opApp] = sym_opApp,
  [sym__base_expr] = sym__base_expr,
  [sym__per_comments] = sym__per_comments,
  [sym__post_comments] = sym__post_comments,
  [sym__expr] = sym__expr,
  [aux_sym_levels_repeat1] = aux_sym_levels_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__end_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_sym] = {
    .visible = true,
    .named = true,
  },
  [sym_nat] = {
    .visible = true,
    .named = true,
  },
  [sym_level_t] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDU] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_erased] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym__end_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_levels] = {
    .visible = true,
    .named = true,
  },
  [sym__level] = {
    .visible = false,
    .named = true,
  },
  [sym_level_add] = {
    .visible = true,
    .named = true,
  },
  [sym_universe] = {
    .visible = true,
    .named = true,
  },
  [sym_named] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_opTyped] = {
    .visible = true,
    .named = true,
  },
  [sym_opApp] = {
    .visible = true,
    .named = true,
  },
  [sym__base_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__per_comments] = {
    .visible = false,
    .named = true,
  },
  [sym__post_comments] = {
    .visible = false,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_levels_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_erasure = 2,
  field_name = 3,
  field_rest = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_erasure] = "erasure",
  [field_name] = "name",
  [field_rest] = "rest",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 3},
    {field_name, 1},
  [2] =
    {field_body, 3},
    {field_name, 1},
    {field_rest, 5},
  [5] =
    {field_body, 6},
    {field_name, 1},
    {field_type, 3},
  [8] =
    {field_body, 7},
    {field_erasure, 5},
    {field_name, 1},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 32,
  [39] = 39,
  [40] = 29,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        ' ', 2,
        '#', 13,
        '\'', 36,
        '(', 37,
        ')', 40,
        '+', 29,
        ',', 28,
        '-', 8,
        ':', 39,
        ';', 33,
        '@', 31,
        '[', 34,
        ']', 35,
        '{', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 2,
        '#', 13,
        '\'', 36,
        '(', 37,
        ')', 40,
        '+', 29,
        ',', 28,
        '-', 8,
        ':', 39,
        ';', 33,
        '@', 31,
        '[', 34,
        ']', 35,
        '{', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 2,
        '#', 13,
        '\'', 36,
        '(', 37,
        ')', 40,
        '+', 29,
        ',', 28,
        '-', 9,
        ':', 39,
        ';', 33,
        '=', 3,
        '@', 31,
        '[', 34,
        ']', 35,
        '{', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '{') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(20);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '>') ADVANCE(41);
      if (lookahead == '}') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(42);
      END_STATE();
    case 13:
      if (lookahead == 'L') ADVANCE(27);
      if (lookahead == 'U') ADVANCE(30);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '#', 13,
        '\'', 36,
        '(', 37,
        ')', 40,
        '+', 29,
        ',', 28,
        '-', 7,
        ':', 12,
        ';', 33,
        '@', 31,
        '[', 34,
        ']', 35,
        '{', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__end_comment_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__end_comment_token1);
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '{') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(20);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__end_comment_token1);
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '{') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(20);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__end_comment_token1);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__end_comment_token1);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '}') ADVANCE(18);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__end_comment_token1);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_sym);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_nat);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_level_t);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_POUNDU);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_erased);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '>') ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 14},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 14},
  [30] = {.lex_state = 14},
  [31] = {.lex_state = 14},
  [32] = {.lex_state = 14},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 11},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment_line] = ACTIONS(1),
    [anon_sym_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_DASH_RBRACE] = ACTIONS(1),
    [sym_sym] = ACTIONS(1),
    [sym_nat] = ACTIONS(1),
    [sym_level_t] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_POUNDU] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_erased] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COLON_GT] = ACTIONS(1),
  },
  [1] = {
    [sym_expr] = STATE(45),
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(12),
    [sym_named] = STATE(12),
    [sym_bracket] = STATE(12),
    [sym_lambda] = STATE(12),
    [sym_opTyped] = STATE(12),
    [sym_opApp] = STATE(12),
    [sym__base_expr] = STATE(12),
    [sym__per_comments] = STATE(12),
    [sym__post_comments] = STATE(12),
    [sym__expr] = STATE(12),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(7),
    [sym_nat] = ACTIONS(7),
    [sym_level_t] = ACTIONS(7),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [2] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(17),
    [sym_nat] = ACTIONS(17),
    [sym_level_t] = ACTIONS(17),
    [anon_sym_POUNDU] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(17),
    [sym_erased] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(17),
    [anon_sym_COLON_GT] = ACTIONS(17),
  },
  [3] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_level_t] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(21),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_COLON_GT] = ACTIONS(27),
  },
  [4] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_comment_line] = ACTIONS(29),
    [anon_sym_LBRACE_DASH] = ACTIONS(29),
    [sym_sym] = ACTIONS(29),
    [sym_nat] = ACTIONS(29),
    [sym_level_t] = ACTIONS(29),
    [anon_sym_POUNDU] = ACTIONS(29),
    [anon_sym_AT] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(29),
    [sym_erased] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_COLON_GT] = ACTIONS(29),
  },
  [5] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(9),
    [sym_named] = STATE(9),
    [sym_bracket] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_opTyped] = STATE(9),
    [sym_opApp] = STATE(9),
    [sym__base_expr] = STATE(9),
    [sym__per_comments] = STATE(9),
    [sym__post_comments] = STATE(9),
    [sym__expr] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(33),
    [sym_nat] = ACTIONS(33),
    [sym_level_t] = ACTIONS(33),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(31),
    [sym_erased] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_COLON_GT] = ACTIONS(31),
  },
  [6] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(4),
    [sym_named] = STATE(4),
    [sym_bracket] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym_opTyped] = STATE(4),
    [sym_opApp] = STATE(4),
    [sym__base_expr] = STATE(4),
    [sym__per_comments] = STATE(4),
    [sym__post_comments] = STATE(4),
    [sym__expr] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(37),
    [sym_nat] = ACTIONS(37),
    [sym_level_t] = ACTIONS(37),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(35),
    [sym_erased] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_COLON_GT] = ACTIONS(35),
  },
  [7] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_level_t] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_COLON_GT] = ACTIONS(27),
  },
  [8] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_level_t] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(41),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_COLON_GT] = ACTIONS(41),
  },
  [9] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_comment_line] = ACTIONS(43),
    [anon_sym_LBRACE_DASH] = ACTIONS(43),
    [sym_sym] = ACTIONS(43),
    [sym_nat] = ACTIONS(43),
    [sym_level_t] = ACTIONS(43),
    [anon_sym_POUNDU] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [sym_erased] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_COLON_GT] = ACTIONS(43),
  },
  [10] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(9),
    [sym_named] = STATE(9),
    [sym_bracket] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym_opTyped] = STATE(9),
    [sym_opApp] = STATE(9),
    [sym__base_expr] = STATE(9),
    [sym__per_comments] = STATE(9),
    [sym__post_comments] = STATE(9),
    [sym__expr] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(33),
    [sym_nat] = ACTIONS(33),
    [sym_level_t] = ACTIONS(33),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(45),
    [sym_erased] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_COLON_GT] = ACTIONS(45),
  },
  [11] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(47),
    [sym_nat] = ACTIONS(47),
    [sym_level_t] = ACTIONS(47),
    [anon_sym_POUNDU] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(47),
    [anon_sym_RBRACK] = ACTIONS(47),
    [sym_erased] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_COLON_GT] = ACTIONS(47),
  },
  [12] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_level_t] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_COLON_GT] = ACTIONS(27),
  },
  [13] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_level_t] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(51),
    [anon_sym_COLON_GT] = ACTIONS(27),
  },
  [14] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_level_t] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_COLON_GT] = ACTIONS(27),
  },
  [15] = {
    [sym__comment] = STATE(10),
    [sym_comment_block] = STATE(10),
    [sym_universe] = STATE(11),
    [sym_named] = STATE(11),
    [sym_bracket] = STATE(11),
    [sym_lambda] = STATE(11),
    [sym_opTyped] = STATE(11),
    [sym_opApp] = STATE(11),
    [sym__base_expr] = STATE(11),
    [sym__per_comments] = STATE(11),
    [sym__post_comments] = STATE(11),
    [sym__expr] = STATE(11),
    [sym_comment_line] = ACTIONS(19),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(23),
    [sym_nat] = ACTIONS(23),
    [sym_level_t] = ACTIONS(23),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(55),
    [sym_erased] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_COLON_GT] = ACTIONS(27),
  },
  [16] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(7),
    [sym_named] = STATE(7),
    [sym_bracket] = STATE(7),
    [sym_lambda] = STATE(7),
    [sym_opTyped] = STATE(7),
    [sym_opApp] = STATE(7),
    [sym__base_expr] = STATE(7),
    [sym__per_comments] = STATE(7),
    [sym__post_comments] = STATE(7),
    [sym__expr] = STATE(7),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(57),
    [sym_nat] = ACTIONS(57),
    [sym_level_t] = ACTIONS(57),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [17] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(15),
    [sym_named] = STATE(15),
    [sym_bracket] = STATE(15),
    [sym_lambda] = STATE(15),
    [sym_opTyped] = STATE(15),
    [sym_opApp] = STATE(15),
    [sym__base_expr] = STATE(15),
    [sym__per_comments] = STATE(15),
    [sym__post_comments] = STATE(15),
    [sym__expr] = STATE(15),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(59),
    [sym_nat] = ACTIONS(59),
    [sym_level_t] = ACTIONS(59),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [18] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(3),
    [sym_named] = STATE(3),
    [sym_bracket] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym_opTyped] = STATE(3),
    [sym_opApp] = STATE(3),
    [sym__base_expr] = STATE(3),
    [sym__per_comments] = STATE(3),
    [sym__post_comments] = STATE(3),
    [sym__expr] = STATE(3),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(61),
    [sym_nat] = ACTIONS(61),
    [sym_level_t] = ACTIONS(61),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [19] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(14),
    [sym_named] = STATE(14),
    [sym_bracket] = STATE(14),
    [sym_lambda] = STATE(14),
    [sym_opTyped] = STATE(14),
    [sym_opApp] = STATE(14),
    [sym__base_expr] = STATE(14),
    [sym__per_comments] = STATE(14),
    [sym__post_comments] = STATE(14),
    [sym__expr] = STATE(14),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(63),
    [sym_nat] = ACTIONS(63),
    [sym_level_t] = ACTIONS(63),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [20] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(13),
    [sym_named] = STATE(13),
    [sym_bracket] = STATE(13),
    [sym_lambda] = STATE(13),
    [sym_opTyped] = STATE(13),
    [sym_opApp] = STATE(13),
    [sym__base_expr] = STATE(13),
    [sym__per_comments] = STATE(13),
    [sym__post_comments] = STATE(13),
    [sym__expr] = STATE(13),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(65),
    [sym_nat] = ACTIONS(65),
    [sym_level_t] = ACTIONS(65),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [21] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(2),
    [sym_named] = STATE(2),
    [sym_bracket] = STATE(2),
    [sym_lambda] = STATE(2),
    [sym_opTyped] = STATE(2),
    [sym_opApp] = STATE(2),
    [sym__base_expr] = STATE(2),
    [sym__per_comments] = STATE(2),
    [sym__post_comments] = STATE(2),
    [sym__expr] = STATE(2),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(67),
    [sym_nat] = ACTIONS(67),
    [sym_level_t] = ACTIONS(67),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
  [22] = {
    [sym__comment] = STATE(5),
    [sym_comment_block] = STATE(5),
    [sym_universe] = STATE(8),
    [sym_named] = STATE(8),
    [sym_bracket] = STATE(8),
    [sym_lambda] = STATE(8),
    [sym_opTyped] = STATE(8),
    [sym_opApp] = STATE(8),
    [sym__base_expr] = STATE(8),
    [sym__per_comments] = STATE(8),
    [sym__post_comments] = STATE(8),
    [sym__expr] = STATE(8),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_LBRACE_DASH] = ACTIONS(5),
    [sym_sym] = ACTIONS(69),
    [sym_nat] = ACTIONS(69),
    [sym_level_t] = ACTIONS(69),
    [anon_sym_POUNDU] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(73), 1,
      anon_sym_PLUS,
    ACTIONS(71), 16,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [22] = 3,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      aux_sym_levels_repeat1,
    ACTIONS(75), 15,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [46] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      aux_sym_levels_repeat1,
    ACTIONS(79), 15,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [70] = 3,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_levels_repeat1,
    ACTIONS(84), 15,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [94] = 1,
    ACTIONS(86), 16,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [113] = 1,
    ACTIONS(79), 16,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_COMMA,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [132] = 1,
    ACTIONS(88), 15,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [150] = 1,
    ACTIONS(90), 15,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [168] = 1,
    ACTIONS(92), 15,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [186] = 1,
    ACTIONS(94), 15,
      ts_builtin_sym_end,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      sym_sym,
      sym_nat,
      sym_level_t,
      anon_sym_POUNDU,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_erased,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_GT,
  [204] = 5,
    ACTIONS(98), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(100), 1,
      anon_sym_DASH_RBRACE,
    STATE(32), 1,
      sym__end_comment,
    ACTIONS(96), 2,
      sym_comment_line,
      aux_sym__end_comment_token1,
    STATE(35), 2,
      sym__comment,
      sym_comment_block,
  [222] = 5,
    ACTIONS(98), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(104), 1,
      anon_sym_DASH_RBRACE,
    STATE(38), 1,
      sym__end_comment,
    ACTIONS(102), 2,
      sym_comment_line,
      aux_sym__end_comment_token1,
    STATE(36), 2,
      sym__comment,
      sym_comment_block,
  [240] = 5,
    ACTIONS(98), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(106), 1,
      anon_sym_DASH_RBRACE,
    STATE(29), 1,
      sym__end_comment,
    ACTIONS(96), 2,
      sym_comment_line,
      aux_sym__end_comment_token1,
    STATE(35), 2,
      sym__comment,
      sym_comment_block,
  [258] = 5,
    ACTIONS(98), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(108), 1,
      anon_sym_DASH_RBRACE,
    STATE(40), 1,
      sym__end_comment,
    ACTIONS(102), 2,
      sym_comment_line,
      aux_sym__end_comment_token1,
    STATE(36), 2,
      sym__comment,
      sym_comment_block,
  [276] = 4,
    ACTIONS(110), 1,
      sym_sym,
    ACTIONS(112), 1,
      sym_nat,
    STATE(31), 1,
      sym_levels,
    STATE(26), 2,
      sym__level,
      sym_level_add,
  [290] = 1,
    ACTIONS(114), 4,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      anon_sym_DASH_RBRACE,
      aux_sym__end_comment_token1,
  [297] = 3,
    ACTIONS(110), 1,
      sym_sym,
    ACTIONS(116), 1,
      sym_nat,
    STATE(28), 2,
      sym__level,
      sym_level_add,
  [308] = 1,
    ACTIONS(118), 4,
      sym_comment_line,
      anon_sym_LBRACE_DASH,
      anon_sym_DASH_RBRACE,
      aux_sym__end_comment_token1,
  [315] = 2,
    ACTIONS(120), 1,
      sym_erased,
    ACTIONS(122), 1,
      anon_sym_DASH_GT,
  [322] = 1,
    ACTIONS(124), 1,
      anon_sym_COLON,
  [326] = 1,
    ACTIONS(126), 1,
      sym_sym,
  [330] = 1,
    ACTIONS(128), 1,
      anon_sym_DASH_GT,
  [334] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [338] = 1,
    ACTIONS(132), 1,
      sym_sym,
  [342] = 1,
    ACTIONS(134), 1,
      sym_nat,
  [346] = 1,
    ACTIONS(136), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(23)] = 0,
  [SMALL_STATE(24)] = 22,
  [SMALL_STATE(25)] = 46,
  [SMALL_STATE(26)] = 70,
  [SMALL_STATE(27)] = 94,
  [SMALL_STATE(28)] = 113,
  [SMALL_STATE(29)] = 132,
  [SMALL_STATE(30)] = 150,
  [SMALL_STATE(31)] = 168,
  [SMALL_STATE(32)] = 186,
  [SMALL_STATE(33)] = 204,
  [SMALL_STATE(34)] = 222,
  [SMALL_STATE(35)] = 240,
  [SMALL_STATE(36)] = 258,
  [SMALL_STATE(37)] = 276,
  [SMALL_STATE(38)] = 290,
  [SMALL_STATE(39)] = 297,
  [SMALL_STATE(40)] = 308,
  [SMALL_STATE(41)] = 315,
  [SMALL_STATE(42)] = 322,
  [SMALL_STATE(43)] = 326,
  [SMALL_STATE(44)] = 330,
  [SMALL_STATE(45)] = 334,
  [SMALL_STATE(46)] = 338,
  [SMALL_STATE(47)] = 342,
  [SMALL_STATE(48)] = 346,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opApp, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 7, 0, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named, 6, 0, 2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named, 5, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 8, 0, 4),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opTyped, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__per_comments, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__post_comments, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opApp, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__level, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_levels, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_levels_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_levels_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_levels, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_level_add, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_comment, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_universe, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_block, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__end_comment, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [130] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lambdaCube(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
